# -*- coding: utf-8 -*-
# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: hornbeam.proto

from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='hornbeam.proto',
  package='',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=b'\n\x0ehornbeam.proto\"=\n\tCondition\x12\x0f\n\x07op_name\x18\x01 \x01(\t\x12\x10\n\x08key_name\x18\x02 \x01(\t\x12\r\n\x05value\x18\x03 \x01(\t\"\xa2\x01\n\tStatement\x12!\n\x06\x65\x66\x66\x65\x63t\x18\x01 \x01(\x0e\x32\x11.Statement.Effect\x12\x11\n\tprincipal\x18\x02 \x01(\t\x12\x0e\n\x06\x61\x63tion\x18\x03 \x01(\t\x12\x10\n\x08resource\x18\x04 \x01(\t\x12\x1e\n\nconditions\x18\x05 \x03(\x0b\x32\n.Condition\"\x1d\n\x06\x45\x66\x66\x65\x63t\x12\t\n\x05\x41LLOW\x10\x00\x12\x08\n\x04\x44\x45NY\x10\x01\"(\n\x06Policy\x12\x1e\n\nstatements\x18\x01 \x03(\x0b\x32\n.Statement\"I\n\x16\x43omparePoliciesRequest\x12\x16\n\x05\x66irst\x18\x01 \x01(\x0b\x32\x07.Policy\x12\x17\n\x06second\x18\x02 \x01(\x0b\x32\x07.Policy\"\xb0\x01\n\x15\x43omparePolicyResponse\x12-\n\x06result\x18\x01 \x01(\x0e\x32\x1d.ComparePolicyResponse.Result\"h\n\x06Result\x12\n\n\x06UNUSED\x10\x00\x12\t\n\x05\x45QUAL\x10\x01\x12\x13\n\x0fMORE_PERMISSIVE\x10\x02\x12\x13\n\x0fLESS_PERMISSIVE\x10\x03\x12\x10\n\x0cINCOMPARABLE\x10\x04\x12\x0b\n\x07UNKNOWN\x10\x05\x32P\n\x08Hornbeam\x12\x44\n\x0f\x43omparePolicies\x12\x17.ComparePoliciesRequest\x1a\x16.ComparePolicyResponse\"\x00\x62\x06proto3'
)



_STATEMENT_EFFECT = _descriptor.EnumDescriptor(
  name='Effect',
  full_name='Statement.Effect',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='ALLOW', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='DENY', index=1, number=1,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=215,
  serialized_end=244,
)
_sym_db.RegisterEnumDescriptor(_STATEMENT_EFFECT)

_COMPAREPOLICYRESPONSE_RESULT = _descriptor.EnumDescriptor(
  name='Result',
  full_name='ComparePolicyResponse.Result',
  filename=None,
  file=DESCRIPTOR,
  values=[
    _descriptor.EnumValueDescriptor(
      name='UNUSED', index=0, number=0,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='EQUAL', index=1, number=1,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='MORE_PERMISSIVE', index=2, number=2,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='LESS_PERMISSIVE', index=3, number=3,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='INCOMPARABLE', index=4, number=4,
      serialized_options=None,
      type=None),
    _descriptor.EnumValueDescriptor(
      name='UNKNOWN', index=5, number=5,
      serialized_options=None,
      type=None),
  ],
  containing_type=None,
  serialized_options=None,
  serialized_start=436,
  serialized_end=540,
)
_sym_db.RegisterEnumDescriptor(_COMPAREPOLICYRESPONSE_RESULT)


_CONDITION = _descriptor.Descriptor(
  name='Condition',
  full_name='Condition',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='op_name', full_name='Condition.op_name', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='key_name', full_name='Condition.key_name', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='value', full_name='Condition.value', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=18,
  serialized_end=79,
)


_STATEMENT = _descriptor.Descriptor(
  name='Statement',
  full_name='Statement',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='effect', full_name='Statement.effect', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='principal', full_name='Statement.principal', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='action', full_name='Statement.action', index=2,
      number=3, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='resource', full_name='Statement.resource', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=b"".decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='conditions', full_name='Statement.conditions', index=4,
      number=5, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _STATEMENT_EFFECT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=82,
  serialized_end=244,
)


_POLICY = _descriptor.Descriptor(
  name='Policy',
  full_name='Policy',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='statements', full_name='Policy.statements', index=0,
      number=1, type=11, cpp_type=10, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=246,
  serialized_end=286,
)


_COMPAREPOLICIESREQUEST = _descriptor.Descriptor(
  name='ComparePoliciesRequest',
  full_name='ComparePoliciesRequest',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='first', full_name='ComparePoliciesRequest.first', index=0,
      number=1, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='second', full_name='ComparePoliciesRequest.second', index=1,
      number=2, type=11, cpp_type=10, label=1,
      has_default_value=False, default_value=None,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=288,
  serialized_end=361,
)


_COMPAREPOLICYRESPONSE = _descriptor.Descriptor(
  name='ComparePolicyResponse',
  full_name='ComparePolicyResponse',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='result', full_name='ComparePolicyResponse.result', index=0,
      number=1, type=14, cpp_type=8, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
    _COMPAREPOLICYRESPONSE_RESULT,
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=364,
  serialized_end=540,
)

_STATEMENT.fields_by_name['effect'].enum_type = _STATEMENT_EFFECT
_STATEMENT.fields_by_name['conditions'].message_type = _CONDITION
_STATEMENT_EFFECT.containing_type = _STATEMENT
_POLICY.fields_by_name['statements'].message_type = _STATEMENT
_COMPAREPOLICIESREQUEST.fields_by_name['first'].message_type = _POLICY
_COMPAREPOLICIESREQUEST.fields_by_name['second'].message_type = _POLICY
_COMPAREPOLICYRESPONSE.fields_by_name['result'].enum_type = _COMPAREPOLICYRESPONSE_RESULT
_COMPAREPOLICYRESPONSE_RESULT.containing_type = _COMPAREPOLICYRESPONSE
DESCRIPTOR.message_types_by_name['Condition'] = _CONDITION
DESCRIPTOR.message_types_by_name['Statement'] = _STATEMENT
DESCRIPTOR.message_types_by_name['Policy'] = _POLICY
DESCRIPTOR.message_types_by_name['ComparePoliciesRequest'] = _COMPAREPOLICIESREQUEST
DESCRIPTOR.message_types_by_name['ComparePolicyResponse'] = _COMPAREPOLICYRESPONSE
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

Condition = _reflection.GeneratedProtocolMessageType('Condition', (_message.Message,), {
  'DESCRIPTOR' : _CONDITION,
  '__module__' : 'hornbeam_pb2'
  # @@protoc_insertion_point(class_scope:Condition)
  })
_sym_db.RegisterMessage(Condition)

Statement = _reflection.GeneratedProtocolMessageType('Statement', (_message.Message,), {
  'DESCRIPTOR' : _STATEMENT,
  '__module__' : 'hornbeam_pb2'
  # @@protoc_insertion_point(class_scope:Statement)
  })
_sym_db.RegisterMessage(Statement)

Policy = _reflection.GeneratedProtocolMessageType('Policy', (_message.Message,), {
  'DESCRIPTOR' : _POLICY,
  '__module__' : 'hornbeam_pb2'
  # @@protoc_insertion_point(class_scope:Policy)
  })
_sym_db.RegisterMessage(Policy)

ComparePoliciesRequest = _reflection.GeneratedProtocolMessageType('ComparePoliciesRequest', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREPOLICIESREQUEST,
  '__module__' : 'hornbeam_pb2'
  # @@protoc_insertion_point(class_scope:ComparePoliciesRequest)
  })
_sym_db.RegisterMessage(ComparePoliciesRequest)

ComparePolicyResponse = _reflection.GeneratedProtocolMessageType('ComparePolicyResponse', (_message.Message,), {
  'DESCRIPTOR' : _COMPAREPOLICYRESPONSE,
  '__module__' : 'hornbeam_pb2'
  # @@protoc_insertion_point(class_scope:ComparePolicyResponse)
  })
_sym_db.RegisterMessage(ComparePolicyResponse)



_HORNBEAM = _descriptor.ServiceDescriptor(
  name='Hornbeam',
  full_name='Hornbeam',
  file=DESCRIPTOR,
  index=0,
  serialized_options=None,
  serialized_start=542,
  serialized_end=622,
  methods=[
  _descriptor.MethodDescriptor(
    name='ComparePolicies',
    full_name='Hornbeam.ComparePolicies',
    index=0,
    containing_service=None,
    input_type=_COMPAREPOLICIESREQUEST,
    output_type=_COMPAREPOLICYRESPONSE,
    serialized_options=None,
  ),
])
_sym_db.RegisterServiceDescriptor(_HORNBEAM)

DESCRIPTOR.services_by_name['Hornbeam'] = _HORNBEAM

# @@protoc_insertion_point(module_scope)
